### ISSUE TITLE
@WithMockKeycloackAuth not found

### ISSUE THREAD

**Issue by rosariop** [ch4mpy/spring-addons#11]
@WithMockKeycloackAuth is not found.
Added following dependency
`
<dependency>
            <groupId>com.c4-soft.springaddons</groupId>
            <artifactId>spring-security-oauth2-test-webmvc-addons</artifactId>
            <version>2.3.1</version>
            <scope>test</scope>
        </dependency>
`

my imports
`
import com.c4_soft.springaddons.security.oauth2.test.mockmvc.ServletUnitTestingSupport;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.keycloak.adapters.springboot.KeycloakSpringBootConfigResolver;
import org.keycloak.adapters.springsecurity.KeycloakSecurityComponents;
import org.mockito.Mockito;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.security.test.context.support.WithMockUser;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;

import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import java.util.ArrayList;
import java.util.List;

import static org.junit.Assert.assertEquals;

@RunWith(SpringRunner.class)
@WebMvcTest(StudentController.class)
@ContextConfiguration(classes = WaterlooApplication.class)
@ComponentScan(basePackageClasses = {KeycloakSecurityComponents.class, KeycloakSpringBootConfigResolver.class})
public class StudentControllerMVCTests extends ServletUnitTestingSupport {}
`

any idea how to fix?

**Comment by jhobeck** [comment]
Your Maven dependency is correct.  Are you getting a compile error when you import the following?

`
import com.c4_soft.springaddons.security.oauth2.test.annotations.keycloak.WithMockKeycloakAuth;
`

**Comment by ch4mpy** [comment]
@rosariop, I see neither `WithMockKeycloakAuth` import (should be as given by @jhobeck) nor usage in the code you provide. So I can't help much.

Please refer to [GreetingControllerAnnotatedTest](https://github.com/ch4mpy/spring-addons/blob/master/spring-security-oauth2-test-webmvc-addons/src/test/java/com/c4_soft/springaddons/samples/webmvc/keycloak/web/GreetingControllerAnnotatedTest.java) for an annotation sample or [GreetingControllerMockMvcPostProcessorTest](https://github.com/ch4mpy/spring-addons/blob/master/spring-security-oauth2-test-webmvc-addons/src/test/java/com/c4_soft/springaddons/samples/webmvc/keycloak/web/GreetingControllerMockMvcPostProcessorTest.java) for a MockMvc fluent API sample

**Comment by rosariop** [comment]
Hey, sorry, did not want to spam, thats why I didn't post the full code:
`@Test
    @WithMockKeycloakAuth
	public void shouldGetStudentsBetweenTimesWithSchool() throws Exception{
        List<Student> students = new ArrayList<>();
		List<Student> returnList = new ArrayList<>();

    `

`import com.c4_soft.springaddons.security.oauth2.test.annotations.keycloak.*;`

**Comment by ch4mpy** [comment]
Two thing:

1. this is not the same error as yesterday, is it? Added some missing import?
2. according to the stack trace, exception occurs in keycloak configuration because of missing `keycloak.realm` property

I suggest you get a closer look at [GreetingControllerAnnotatedTest](https://github.com/ch4mpy/spring-addons/blob/master/spring-security-oauth2-test-webmvc-addons/src/test/java/com/c4_soft/springaddons/samples/webmvc/keycloak/web/GreetingControllerAnnotatedTest.java), with special care to those three lines: 
``` java
// because this sample stands in the middle of non spring-boot-keycloak projects, keycloakproperties are isolated in
// application-keycloak.properties
@ActiveProfiles("keycloak")
```
and then double check that you test `apllication.properties` contains values for the Keykloak properties defined in the [`application-keycloak.properties`](https://github.com/ch4mpy/spring-addons/blob/master/spring-security-oauth2-test-webmvc-addons/src/test/resources/application-keycloak.properties) referenced in the comment

**Comment by rosariop** [comment]
```yml
keycloak:
    realm: drivingschool
    auth-server-url: http://localhost:8081/auth
    ssl-required: external
    resource: client-interface
    use-resource-role-mappings: true
    credentials:
        secret: xxx
    bearer-only: true
```

thats my application.yml file. Just to clear this for me: Is this an integration test or a unit-test? do i have to have a keycloak running or not? Right now my keycloak service is offline because i want to unit-test..

**Comment by ch4mpy** [comment]
This is unit-test. Keycloak can be offline. Keycloak lib just throws an exception if configuration isn't found.

To see my tests, including `GreetingControllerAnnotatedTest`, pass without any Keycloak instance up, you can:
``` bash
git clone https://github.com/ch4mpy/spring-addons.git
cd spring-addons
./mvnw test
```
This would also enable you to browse samples with your favorite IDE and debug some tests.

**Comment by rosariop** [comment]
do you have a discord server? I still have no clue why its not working :(

**Comment by ch4mpy** [comment]
No I don't, and quite busy at work to be honest.

Can you confirm `GreetingControllerAnnotatedTest` passes ?

If so, it should be close enough to the test your trying to write. Just diff it (and conf files) with your code. I'm pretty sure what your facing is spring-test miss-use (not directly related to this lib)

**Comment by rosariop** [comment]
yes they pass. Sorry.

**Comment by ch4mpy** [comment]
@rosariop please reopen this ticket if you face a problem involving this lib directly (stack trace involving `com.c4_soft.springaddons`).

If the samples I provide are not enough for you to get started, you might open a ticket on stack-overflow and link it here, I'll try to have a look.
