### ISSUE TITLE
CSRF cookie_accessible_from_js produce 403 Forbidden on PUT requests

### ISSUE THREAD

**Issue by Cybelius** [ch4mpy/spring-addons#138]
**Describe the bug**
I am following the bff tutorial and the logout endpoint seems to have an issue when using a PUT method. The request is ended with a 403 FORBIDDEN code and the response is: `An expected CSRF token cannot be found`.

This leads to NOT triggering the logout process for cognito or auht0 providers.

To make it works we need to `disable csrf` but I guess this is not the goal.

**Expected behavior**
According to your tutorial and source code, is making PUT and POST requests working with `cookie_accessible_from_js` csrf option really possible?

**Comment by ch4mpy** [comment]
@Cybelius I'm sorry you jumped in right at the moment that bug was there.

Thank you for figuring out it was just fixed and closing your issue.
