### ISSUE TITLE
can not find symbol

### ISSUE THREAD

**Issue by litanyue** [ch4mpy/spring-addons#16]
Hi, I tried to use the advice you mentioned in https://stackoverflow.com/questions/51711268/how-to-test-keycloak-authentication-in-spring-boot-application to test keycloak,but i found that there seemed to be a lack of variables in the source code.

you mentioned the variable ”privateClaims“，but i can not find in annotation @WithMockKeycloakAuth.

thanks for your reply.

`@WithMockKeycloakAuth(
            authorities = { "USER", "AUTHORIZED_PERSONNEL" },
            id = @IdTokenClaims(sub = "42"),
            oidc = @OidcStandardClaims(
                    email = "ch4mp@c4-soft.com",
                    emailVerified = true,
                    nickName = "Tonton-Pirate",
                    preferredUsername = "ch4mpy"),
            **privateClaims** = @ClaimSet(stringClaims = @StringClaim(name = "foo", value = "bar")))`

**Comment by ch4mpy** [comment]
`privateClaims` was renamed to `otherClaims` in `2.4.1` this is how it is named in `KeycloakAuthenticationToken` because (forgot it in changelog)
