### ISSUE TITLE
Multitenancy with spring boot and keycloak

### ISSUE THREAD

**Issue by tha022** [ch4mpy/spring-addons#18]
Hi guys

I implemented multi-tenancy support for Spring Boot and Keycloak following this [guide](https://www.czetsuyatech.com/2020/11/how-to-implement-multitenancy-with-spring-boot-and-keycloak.html), but after that my tests doesn't run correctly anymore, I get HTTP 403. 

```
@WithMockKeycloakAuth(
            authorities = "user",
            otherClaims = @ClaimSet(
                    stringClaims = @StringClaim(name = "ssn", value = "03058241111")
            )
    )
```
I tried to debug through the code described in the blog and this spring-addons lib, but didn't manage to find a clue.

Any help, advice or pointer in right direction would be highly appreciated.

Thanks in advance!

**Comment by ch4mpy** [comment]
Hi Thomas,

For some reason I wasn't notified for this issue creation and missed it. Sorry. Hope you found a wait to solve your issue :/

If not, would you share the security constraints you configured for the endpoint you get a 403 from ?
Any reference to an `Authentication` impl in method signature ?
Did you check at runtime you actually get a `KeycloakAuthenticationToken` from `SecurityContext` (set a break-point in a controller running in debug and inspect `Authentication` type and structure) ?

**Comment by ch4mpy** [comment]
Fell like I'll never have enough feedback to investigate.
Plz re-open if I'm wrong.
