### ISSUE TITLE
The dependency spring-addons-webflux-jwt-resource-server that is mentioned in webflux-jwt-default sample Readme is not used anywhere

### ISSUE THREAD

**Issue by russmikitiuk** [ch4mpy/spring-addons#223]
**Describe the bug**
The Readme file of the sample project "Reactive Resource Server With JWT Decoder Using spring-addons-webflux-jwt-resource-server" (https://github.com/ch4mpy/spring-addons/tree/master/samples/webflux-jwt-default#readme) states:

> It is worth noting that, compared to [reactive-resource-server tutorial](https://github.com/ch4mpy/spring-addons/tree/master/samples/tutorials/reactive-resource-server), we do not depend on OAuth2 Resource Server. Instead, we'll use [spring-addons-webflux-jwt-resource-server](https://central.sonatype.com/artifact/com.c4-soft.springaddons/spring-addons-webflux-jwt-resource-server/6.1.5), a thin wrapper around it, which pushes auto-configuration to a next level:
> 
> <dependency>
>     <groupId>com.c4-soft.springaddons</groupId>
>     <artifactId>spring-addons-webflux-jwt-resource-server</artifactId>
>     <version>${spring-addons.version}</version>
> </dependency>

However, that dependency is not used anywhere in the spring-addons repo. Also, the repo for that dependency does not exist at the link https://github.com/ch4mpy/spring-addons/tree/master/webflux/spring-addons-webflux-jwt-resource-server that is shared in the Readme file. So, it would be good to have the Readme file updated. Thanks

**Code sample**
N/A

**Expected behavior**
I expected the dependency mentioned in the description to be included in the pom.xml and the repo for that dependency to be present at the link shared in the Readme file.

**Additional context**

**Comment by ch4mpy** [comment]
The sample and tutorials sources were updated when introducing the `7.0.0` breaking changes, but the READMEs didn't follow.

I finally took the time to update the samples and tutorials READMEs. Also, the samples READMEs were missing the disclaimer asking to copy the code from sources instead of the README.
