### ISSUE TITLE
Problems with keycloak roles and authorities

### ISSUE THREAD

**Issue by teuber789** [ch4mpy/spring-addons#23]
Hey @ch4mpy ,

First of all, many thanks for this project! It really has made testing soooo much easier!

I've run into a small problem with authorities and roles created by the `@WithMockKeycloakAuth` annotation.

**Regular roles work for the service**

I've created a small test service that has a simple controller:

```java
@RestController
@RequestMapping("/test")
public class TestController {

    @RolesAllowed({"ADMIN", "USER"})
    @PostMapping(value = "getroles")
    public String getRoles(@AuthenticationPrincipal KeycloakPrincipal<KeycloakSecurityContext> principal) {
        String id = principalHelper.getId(principal).get();
        Set<String> roles = principalHelper.getRoles(principal);
        return String.format("User %s has roles %s", id, String.join(",", roles));
    }
}
```

The service starts up and works as expected. Any keycloak token that has `ADMIN` or `USER` in the realm roles array of their JWT is allowed access to the endpoint. Any token that doesn't have one of those roles isn't. It works great.

Here's an example of the `realm_access` section of the payload from a test token (after being decoded using jwt.io, that is):
```json
  "realm_access": {
    "roles": [
      "USER"
    ]
  },
```
The token that this section is taken from is known good; it works exactly as you would expect it to against the service.

**Testing roles aren't the same**

However, roles can't be tested the same way. Consider this test:

```java
    @Test
    @WithMockKeycloakAuth(
            authorities = {
                    "ROLE_ADMIN",
                    "ROLE_USER",
            },
            id = @IdTokenClaims(sub = "asdf1234")
    )
    void test1() throws Exception {
        MvcResult result = mvc.perform(
                post("/test/getroles"))
                .andExpect(status().isOk())
                .andReturn();
        assertThat(result.getResponse().getContentAsString()).isEqualTo("User asdf1234 has roles ADMIN,USER");
    }
```
You would expect that the roles for the token would be `ADMIN` and `USER`, but they're `ROLE_ADMIN` and `ROLE_USER`. Consequently, this test fails because the result string ends up being `User asdf1234 has roles ROLE_ADMIN,ROLE_USER`.

The next natural step is to remove the `ROLE_` prefix from the authorities:
```java
    @Test
    @WithMockKeycloakAuth(
            authorities = {
                    "ADMIN",
                    "USER",
            },
            id = @IdTokenClaims(sub = "asdf1234")
    )
    void test2() throws Exception {
        MvcResult result = mvc.perform(
                post("/test/getroles"))
                .andExpect(status().isOk())
                .andReturn();
        assertThat(result.getResponse().getContentAsString()).isEqualTo("User asdf1234 has roles ADMIN,USER");
    }
```
However, this fails with a 403 because the `RolesAllowed` annotation in the controller is expecting an authority value of `ROLE_ADMIN` or `ROLE_USER`.

I've attached my demo service to this ticket. To run the tests and see them fail, run `./gradlew clean test`.

[keycloak-springboot-microservice.zip](https://github.com/ch4mpy/spring-addons/files/6818508/keycloak-springboot-microservice.zip)

Thanks!

**Comment by teuber789** [comment]
Also - could this be related to #3 ?

**Comment by ch4mpy** [comment]
Is it possible that you have different `GrantedAuthoritiesMapper` during tests and at runtime ? Can you double check and provide me with implementations used in both cases ?

As can be seen [here](https://github.com/ch4mpy/spring-addons/blob/4781d22c609c369f0ba601b13751c2a53605785e/spring-security-oauth2-test-addons/src/main/java/com/c4_soft/springaddons/security/oauth2/test/keycloak/KeycloakAuthenticationTokenTestingBuilder.java#L73), I use registered `authoritiesMapper` to transform provided authorities.
And as can be seen [there](https://github.com/ch4mpy/spring-addons/blob/4781d22c609c369f0ba601b13751c2a53605785e/spring-security-oauth2-test-addons/src/main/java/com/c4_soft/springaddons/security/oauth2/test/keycloak/KeycloakAuthenticationTokenTestingBuilder.java#L58), `NullAuthoritiesMapper` is used by default (no-op mapper).

Maybe do you have a `SimpleAuthorityMapper` at runtime (which adds `ROLE_` prefix by default) and `NullAuthoritiesMapper` (which does nothing) wired during tests ?

What I would do in your case:
1. search for a conf wiring a `SimpleAuthorityMapper` at runtime
2. understand why this conf is ignored during tests (maybe conf file is not scanned, maybe `GrantedAuthoritiesMapper` is explicitly set to `NullAuthoritiesMapper` in test conf, ...)
3. fix test conf

**Comment by ch4mpy** [comment]
I got it:
You override `GrantedAuthoritiesMapper` with `SimpleAuthoritiesMapper` in `KeycloakWebSecurityConfigurerAdapter` but don't expose the bean. As a consequence my lib uses default one which is `NullAuthoritiesMapper`.

In `KeycloakWebSecurityConfigurerAdapter`, just replace
```java
    @Autowired
    public void configureGlobal(AuthenticationManagerBuilder auth) {
        KeycloakAuthenticationProvider keycloakAuthenticationProvider = keycloakAuthenticationProvider();
        keycloakAuthenticationProvider.setGrantedAuthoritiesMapper(new SimpleAuthorityMapper());
        auth.authenticationProvider(keycloakAuthenticationProvider);
    }
```
with
```java

    @Autowired
    public void configureGlobal(AuthenticationManagerBuilder auth) {
        KeycloakAuthenticationProvider keycloakAuthenticationProvider = keycloakAuthenticationProvider();
        keycloakAuthenticationProvider.setGrantedAuthoritiesMapper(authoritiesMapper());
        auth.authenticationProvider(keycloakAuthenticationProvider);
    }
    
	@Bean GrantedAuthoritiesMapper authoritiesMapper() {
		return new SimpleAuthorityMapper();
	}
```
and your second test will pass.

P.S.
please close the ticket if this answers your question.

**Comment by teuber789** [comment]
Hey, that worked perfectly! I wasn't aware that I could needed to expose the authorities mapper bean in order to keep the role mapping between the service and the tests consistent. It's good to know now.

Many thanks!
