### ISSUE TITLE
Service Layer Authentication with Keycloak Not working

### ISSUE THREAD

**Issue by v20gupta** [ch4mpy/spring-addons#28]
@ch4mpy 
Keycloak: 14
SpringBoot: 2.5.2

SecurityConfig;

``` java
@KeycloakConfiguration
@EnableGlobalMethodSecurity(prePostEnabled = true)
public class SecurityConfig extends KeycloakWebSecurityConfigurerAdapter {

    private static final String[] AUTH_WHITELIST = {
            "/swagger-resources/**",
            "/swagger-ui/**",
            "/v3/api-docs/**",
            "/actuator/**"
    };

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        super.configure(http);
        // TODO: Need to reactivate CSRF. Currently blocking POST/PUT/DELETE request if enable
        http.csrf().disable();
        http.authorizeRequests()
                .antMatchers(AUTH_WHITELIST).permitAll()
                .antMatchers("/aircraft/**").hasRole(KeycloakRole.aircraft.roleReadName)
                .antMatchers("/**").authenticated();
    }
    @Bean
    @Override
    protected SessionAuthenticationStrategy sessionAuthenticationStrategy() {
        return new RegisterSessionAuthenticationStrategy(new SessionRegistryImpl());
    }

    @Bean
    @Primary
    public KeycloakSpringBootConfigResolver KeycloakConfigResolver() {
        return new KeycloakSpringBootConfigResolver();
    }

    @Autowired
    public void configureGlobal(AuthenticationManagerBuilder auth) {
        KeycloakAuthenticationProvider keycloakAuthenticationProvider = keycloakAuthenticationProvider();
        keycloakAuthenticationProvider.setGrantedAuthoritiesMapper(new SimpleAuthorityMapper());
        auth.authenticationProvider(keycloakAuthenticationProvider);
    }

    @Bean
    @Override
    @ConditionalOnMissingBean(HttpSessionManager.class)
    protected HttpSessionManager httpSessionManager() {
        return new HttpSessionManager();
    }

}
```

ServiceTest:

``` java
@ExtendWith(MockitoExtension.class)
@Import(AirportServiceTest.TestConfig.class)
class AirportServiceTest {

    @Mock
    private AirportDao airportDao;

    @InjectMocks
    private AirportService airportService;


    @Test
    @WithMockKeycloakAuth(authorities = "ROLE_std_airport_read", oidc = @OidcStandardClaims(preferredUsername  = "abc"))
    public void createAirportWithoutAuthority() {
        Mockito.when(airportDao.save(any())).thenReturn(airport1);
        airportService.createAirport(airportReqDto1);
        verify(airportDao,times(1)).save(any());
    }

    @TestConfiguration(proxyBeanMethods = false)
    @EnableGlobalMethodSecurity(prePostEnabled = true)
    @Import({ AirportService.class })
    public static class TestConfig {
        @Bean
        public GrantedAuthoritiesMapper authoritiesMapper() {
            return new SimpleAuthorityMapper();
        }
    }

}
```

**Comment by ch4mpy** [comment]
Hi @v20gupta , may I ask you your procedure to create this issue? I thought I had set-up issues auto assignement, but apparently there is a path I missed.

Keycloak security does work on service layer. [Unit tests](https://github.com/ch4mpy/spring-addons/blob/master/spring-security-oauth2-test-webmvc-addons/src/test/java/com/c4_soft/springaddons/samples/webmvc/keycloak/service/KeycloakMessageServiceTest.java) would not pass otherwise.

Could you please provide me with a complete sample?
I suspect your test configuration to be broken. I suspect `@ExtendWith(MockitoExtension.class)` to be guilty. Maybe should you use `SpringExtension` for spring magic to happen?

**Comment by v20gupta** [comment]
Hi @ch4mpy , I was trying to unit test the keycloak security at the Service layer but my test case are passing even if I have not provide them the role.
@Service
public class AirportService {

	@Autowired
	private AirportDao airportDao;

	private final AirportMapper airportMapper = Mappers.getMapper( AirportMapper.class );

	@PreAuthorize(hasRole('std_airport_create'))
	public AirportRespDto createAirport(AirportReqDto airportReqDto) {
		Airport airport = airportMapper.airportDtoToAirport(airportReqDto);
		return airportMapper.airportToAirportDto(airportDao.save(airport));
	}
}

ServiceTesting:

@ExtendWith(SpringExtension.class)
@Import({AirportServiceTest.TestConfig.class})
class AirportServiceTest {

    @MockBean
    private AirportDao airportDao;

    @Autowired
    private AirportService airportService;

    private AirportReqDto airportReqDto1;
    private AirportReqDto airportReqDto2;
    private Airport airport1;
    private Airport airport2;
    private List<Airport> airportList;
    private List<AirportRespDto> airportRespList;
    private AirportMapper airportMapper;

    @BeforeEach
    public void setUp() {
        airportMapper = Mappers.getMapper( AirportMapper.class );
        airportList = new ArrayList<>();
        airportReqDto1 = AirportReqDto.builder().name("DelhiAirport").country("IND")
                .code("IND01").build();
        airportReqDto2 = AirportReqDto.builder().name("MumbaiAirport").country("IND")
                .code("IND01").build();

        airport1 = airportMapper.airportDtoToAirport(airportReqDto1);
        airport2 = airportMapper.airportDtoToAirport(airportReqDto2);
        airportList.addAll(Stream.of(airport1, airport2).collect(Collectors.toList()));
        airportRespList = airportMapper.airportsToAirportsDto(airportList);


    }
    @AfterEach
    public void tearDown() {
        airportReqDto1 = airportReqDto2 = null;
        airport1 = airport2 = null;
        airportList = null;
    }

    @Test
    @WithMockKeycloakAuth(authorities = "ROLE_std_airport_rea", id = @IdTokenClaims(sub = "abc"))
    public void createAirport() {
        Mockito.when(airportDao.save(any())).thenReturn(airport1);
        airportService.createAirport(airportReqDto1);
        verify(airportDao,times(1)).save(any());
    }
 @TestConfiguration(proxyBeanMethods = false)
    @Import({ AirportService.class })
    public static class TestConfig {
        @Bean
        public GrantedAuthoritiesMapper authoritiesMapper() {
            return new SimpleAuthorityMapper();
        }

    }

}

**Comment by ch4mpy** [comment]
- you haven't answered my 1st question (how have you proceded to create this issue?)
- this is not a complete sample
- markup is not used properly which makes your comments hardly readable
- you have removed `@EnableGlobalMethodSecurity(prePostEnabled = true)` from your test conf

**Comment by v20gupta** [comment]
Thanks ch4mpy issue is resolved with adding @EnableGlobalMethodSecurity(prePostEnabled = true)
