### ISSUE TITLE
Roles vs authorities in @WithMockKeycloackAuth

### ISSUE THREAD

**Issue by pvannierop** [ch4mpy/spring-addons#3]
Hello, I have started using your utils and I am very happy with it. Thank you for sharing your code. I experience the following difficulty:

- In @WithMockKeycloackAuth all roles get prefixed with `ROLE_`. For my purpose this is unwanted behavior, since I would like pass authorities like true authorities w/o the `ROLE_` part. The `ROLE_` prefix is added in _roles()_ method of _KeycloakAuthenticationTokenTestingBuilder_ and I do not see away to suppress this behavior. The docs at the top of the WithMockKeycloackAuth class suggest that the `ROLE_` prefix should be added manually (which is not the case). Also, the default OIDC fields `"offline_access", "uma_authorization" ` seem incompatible with this approach.

```
 * Sample usage:
 *
 * <pre>
 * &#64;Test
 * &#64;WithMockKeycloackAuth({"ROLE_USER", "ROLE_ADMIN"})
 * public void test() {
 *     ...
 * }
 * </pre>
```
I see two solutions to this problem:
1. Remove automatic addition of the `ROLE_` prefix. Roles passed are interpreted as-is.
2. The  @WithMockKeycloackAuth handles an additional `authorities` parameter. Names passed in via this prop are added to the Auth object w/o the `ROLE_` prefix.

I base the distinction between roles and authorizations on the Spring Security naming convention (see https://www.baeldung.com/spring-security-granted-authority-vs-role)

If needed I can do a proposal in a PR. Just let me know whether you have time to work on this.

**Comment by pvannierop** [comment]
@ch4mpy Hmmm, maybe I am misunderstanding how this is supported to work. I will retract this issue until I have researched more.

**Comment by ch4mpy** [comment]
@pvannierop you might have actually pinned a bug:

Default `GrantedAuthoritiesMapper` is `SimpleAuthorityMapper` which adds the `ROLE_` prefix to Keycloak authorities claim entries when building GrantedAuthorities.

So maybe should I rename "roles" to "authorities" in annotation and request post-processor and use `GrantedAuthoritiesMapper` from test context to build granted authorities (instead of `stream.map(SimpleGrantedAuthority::new).collect(...)` ?

**Comment by pvannierop** [comment]
> That means that authorities should be like 'offline_access' in the JWT claims and 'ROLE_offline_access' in KeycloakAuthenticationToken granted-authorities.

Yeah, the behavior is correct. It was me that was not understanding it correctly. I am rather new to Spring Security so please excuse my ignorance. The renaming of roles to authorities helps to understand.

I propose to update the doc at the top of the _@WithMockKeycloakUser_ class and remove the `ROLE_` prefixes:

```
 * &#64;WithMockKeycloakAuth({"ROLE_USER", "ROLE_ADMIN"})
```

becomes

```
 * &#64;WithMockKeycloakAuth({"USER", "ADMIN"})
```

**Comment by ch4mpy** [comment]
@pvannierop updated the javadoc. May we close ?

**Comment by pvannierop** [comment]
@ch4mpy Sure!
