### ISSUE TITLE
Lombok as compile dependency might not be correct (freaks out IDE)

### ISSUE THREAD

**Issue by Mario-Eis** [ch4mpy/spring-addons#31]
This library is very promising!

But at the moment Lombok is added as a compile dependency. This freaks out my IntelliJ IDE, because it detects Lombok in the classpath without using an annotation processor (I am not using Lombok).
I also never used Lombok. But I think adding it as a compile dependency might no be the correct way to use it.

**Comment by Mario-Eis** [comment]
I found some information here: https://projectlombok.org/setup/maven
Seems it should be added as a provided dependency. This would fix my issue.

**Comment by ch4mpy** [comment]
@Mario-Eis good catch. I forgot to set lombok as `provided` when downgrading Java compatibility from 11 to 1.8, will fix.

Meanwile, ou might:
- install Lombok on IntelliJ, it's awsome (giving it a try is adopting it for sure)
- use 3.1.3-jdk11 or 3.1.3-jdk17 if your project allows it

**Comment by ch4mpy** [comment]
Fixed in `3.1.4-jdk1.8`, `3.1.4-jdk11` and `3.1.4-jdk17`.

Thank you for report.

Do not easitate to comment or re-open if you are not satisfied with solution.
