### ISSUE TITLE
`Jwt.id` (jti) isn't been populated with `OpenIdClaims.jti` value

### ISSUE THREAD

**Issue by SrMouraSilva** [ch4mpy/spring-addons#35]
**Describe the bug**

`Jwt.id` (jti) isn't been populated with `OpenIdClaims.jti` value

**Code sample**

```kotlin
@WithMockJwtAuth(
	claims=OpenIdClaims(
		sub="00000000-0000-0000-0000-000000000000", jti="00000000-0000-0000-0000-000000000000", sessionState="00000000-0000-0000-0000-000000000000",
		otherClaims=Claims(stringClaims=[StringClaim(name="id_institucional", value="aa91613e-34b2-488a-94ef-09ac5bef1904")])
	)
)
fun sampleTest() {}
```

If I check the id of Jwt, it appears null: 
```kotlin
val authenticationJwt = authentication as JwtAuthenticationToken
val principal = authenticationJwtprincipal as Jwt

principal.id == null
```

Tested in 
 * Spring Boot 2.6.1
 * com.c4-soft.springaddons:spring-security-oauth2-test-webmvc-addons:3.1.7-jdk17
 * org.springframework.boot:spring-boot-starter-oauth2-resource-server (the version is based on Spring Boot version)

**Expected behavior**
`Jwt.id` be populated based in `jti` value.

**Comment by SrMouraSilva** [comment]
Note: If I use a (redudant) definition in `otherClaims`, then will works
```kotlin
@WithMockJwtAuth(
	claims=OpenIdClaims(
		sub="00000000-0000-0000-0000-000000000000", jti="00000000-0000-0000-0000-000000000000", sessionState="00000000-0000-0000-0000-000000000000",
		otherClaims=Claims(stringClaims=[StringClaim(name="id_institucional", value="aa91613e-34b2-488a-94ef-09ac5bef1904"), StringClaim(name="jti", value="00000000-0000-0000-0000-000000000000")])
	)
)
```

**Comment by ch4mpy** [comment]
This looks like a bug. Will have a look ASAP.

**Comment by ch4mpy** [comment]
@SrMouraSilva thank you for taking time to report.

I just fogot JTI when extracting annotation value. Sorry about that

This bug affects all `@WithMock...`, but the fix works for all of it too.
You can have a look at the commit linked above, it demoes your use-case in a new test.

Release onging. Please comment or re-open if the solution is not what you expected.

**Comment by ch4mpy** [comment]
@SrMouraSilva release `3.1.8` done.

It usually takes about two hours for the libs to be transfered to https://repo1.maven.org/maven2/com/c4-soft/springaddons/spring-security-oauth2-test-addons/

**Comment by SrMouraSilva** [comment]
@ch4mpy. Tested. Thanks!
