### ISSUE TITLE
Use configured `GrantedAuthoritiesMapper` when parsing `@WithMockKeycloakAuth` realm and resource-access roles

### ISSUE THREAD

**Issue by schmitzhermes** [ch4mpy/spring-addons#37]
**Is your feature request related to a problem? Please describe.**
When configuring Keycloak roles (be it realm roles oder client roles) in the token, the `ROLE_` prefix is not set automatically, but Spring Boot prefixes the authorities (aka roles) with `ROLE_` internally. 

**Describe the solution you'd like**
I would like the library to automatically add the `ROLE_` prefix to the authorities (or at least make the prefix configurable in the annotation). 

**Describe alternatives you've considered**
An alternative is to manually add the `ROLE_` prefix to the roles/authorities. But since this is an implementation detail of Spring Boot, it does not feel natural to add this manually. 

**Additional context**
None

**Comment by ch4mpy** [comment]
No, it shouldn't. Prefixing authorities with `ROLE_` is an implementation choice inside authorities mappers and `authorities` in test annotations are designed to hold already mapped authorities (mappers can make any kind of transformation).

At some point, both `authorities` and `roles` where exposed in my test annotations, the second adding the `ROLE_` prefix. This was leading to more confusion than help and I removed the less generic one (couldn't make authorities with other prefix or no prefix at all with `roles`)

**Comment by schmitzhermes** [comment]
Hmm, I agree that this is an implementation choice inside the mappers, but this choice only needs to be made because Spring Boot made the choice to have `ROLE_` as the default prefix (if not configured otherwise), as can be seen here [ExpressionUrlAuthorizationConfigurer.java#L116](https://github.com/spring-projects/spring-security/blob/main/config/src/main/java/org/springframework/security/config/annotation/web/configurers/ExpressionUrlAuthorizationConfigurer.java#L116). 

Maybe it's just my opinion but as this is a library that enhances SPRING, it'd be absolutely sane to apply the spring boot defaults (like `ROLE_`) and let people override them if they want. 

Of course one can override the default prefix in Spring Boot using something like below, but again: it does not feel natural to alter working production code in order to make test working more seamlessly. 
```
@Bean
    fun grantedAuthorityDefaults(): GrantedAuthorityDefaults {
        return GrantedAuthorityDefaults("YOUR_PREFIX")
    }
```

**Comment by ch4mpy** [comment]
Maybe should I remove completely realm and resource access roles adding to authorities to avoid confusion.

You need certain authorities with prefix, suffix, case tweeking or wahtever in a test? Put it like it needs to be in `authorities` property. It's made for that. 

Any spring-boot application explicitely providing a `GrantedAuthoritiesMapper` bean can do about anything with authorities and test annotation can hardly figure out what. Most production spring-boot apps I know configure such a bean.

If you take a look into spring-security-core `org.springframework.security.core.authority.mapping` package you'll see that:
- `SimpleAuthorityMapper` does add `ROLE_` prefix
- `NullAuthoritiesMapper` doesn't

Maybe are you using `hasRole` or `hasAnyRole` rather than `hasAuthority` or `hasAnyAuthority` to think that "ROLE_" prefix is a convention?

**Comment by ch4mpy** [comment]
Anyhow, I'll try to see if I can detect a `GrantedAuthoritiesMapper` `@Bean` in test configuration and use it when extracting Keycloak roles, but not today.

**Comment by schmitzhermes** [comment]
Okay, I do get your point and I also agree (though not wholeheartedly 😄 )
Thanks for looking into it and thank you for the productive discussion and blazingly fast response - this is open source spirit!!

**Comment by schmitzhermes** [comment]
> Maybe are you using hasRole or hasAnyRole rather than hasAuthority or hasAnyAuthority to think that "ROLE_" prefix is a convention?

Yes, I do. My security configuration relies on `hasRole` instead of `hasAuthority` and the `hasRole` convenience method adds the `ROLE_` prefix. But I understand that there are other "authorities" than roles.

**Comment by ch4mpy** [comment]
So looking a little further, configured `GrantedAuthoritiesMapper` [is already injected](https://github.com/ch4mpy/spring-addons/blob/6610739b6ad258d5996bc040148a8bc995ba1eee/spring-security-oauth2-test-addons/src/main/java/com/c4_soft/springaddons/security/oauth2/test/annotations/keycloak/WithMockKeycloakAuth.java#L98) and if something else than NullAuthorityMapper is configured, it should [process authorities](https://github.com/ch4mpy/spring-addons/blob/6610739b6ad258d5996bc040148a8bc995ba1eee/spring-security-oauth2-test-addons/src/main/java/com/c4_soft/springaddons/security/oauth2/test/keycloak/KeycloakAuthenticationTokenTestingBuilder.java#L70).

Can you provide me with your Keycloak configuration?

**Comment by schmitzhermes** [comment]
Okay, I got it now:
* As I am using the `hasRole(...)` function Spring Boot appends `ROLE_` in the SpEL while assessing the roles
* Therefore I needed to configure the `SimpleAuthorityMapper` in my Keycloak configuration
* Your library expects a `GrantedAuthoritiesMapper` to be injected, however imho it's normally not injected, but rather instantiated in place like so: 
```kotlin
@KeycloakConfiguration
@EnableGlobalMethodSecurity(prePostEnabled = true)
class KeycloakSecurityConfiguration : KeycloakWebSecurityConfigurerAdapter() {
    // .. other config
    
    @Autowired
    fun configureGlobal(auth: AuthenticationManagerBuilder) {
        val keycloakAuthenticationProvider = keycloakAuthenticationProvider()
        keycloakAuthenticationProvider.setGrantedAuthoritiesMapper(SimpleAuthorityMapper())
        auth.authenticationProvider(keycloakAuthenticationProvider)
    }
}
```
* This leads to your library not finding the bean and thus, not injecting it

There are two possible solutions now:
1) I don't use `hasRole(..)` but rather `hasAuthority(...)` and can rely on the default implementation `NullAuthoritiesMapper` 
2) I keep on using `hasRole(...)`, but instead of creating the `SimpleAuthorityMapper` in place I expose it as a `@Bean` and your framework picks it up automatically (one drawback: it needs to be registered outside the `KeycloakSecurityConfiguration` since otherwise it'd be a cyclic dependency)

This can be closed then as your library offers everything it should from my perspective. 
Thanks for your amazing work and support!
