### ISSUE TITLE
Resource Access (aka client roles) should be mapped to authorities

### ISSUE THREAD

**Issue by schmitzhermes** [ch4mpy/spring-addons#38]
**Is your feature request related to a problem? Please describe.**
Resource Access (aka client roles) are not mapped as authorities in the current implementation. One has to manually create the roles as authorities (as opposed to realm roles, where the roles are automatically mapped to `authorities`). 

Code Examples: 
```
@Test
@WithMockKeycloakAuth(
    authorities = [ "ROLE_abc" ],
    accessToken = KeycloakAccessToken(
        resourceAccess = [
            KeycloakResourceAccess(resourceId = "client-id", access = KeycloakAccess(roles = ["abc"]))
        ],
    )
)
fun test() {
    // some test
}
```

The `KeycloakResourceAccess` is not mapped as an authority automatically (again: as opposed to realm roles) - in code terms it is imho "missing" here:
[WithMockKeycloakAuth.java#L111](https://github.com/ch4mpy/spring-addons/blob/master/spring-security-oauth2-test-addons/src/main/java/com/c4_soft/springaddons/security/oauth2/test/annotations/keycloak/WithMockKeycloakAuth.java#L111)

**Describe the solution you'd like**
I would like the realm roles to be automatically added as authorities. 

**Describe alternatives you've considered**
An alternative is to manually add the client role to the `authorities` field in the `WithMockKeycloakAuth` annotation, but this feels unnatural as it's somehow entered twice. 

**Additional context**
None.

**Comment by ch4mpy** [comment]
Hi @schmitzhermes and thank you for this detailed issue report.

You are right, it seems that resource access mapping is missing just where you spotted. Will fix asap.

As a side note, you shouldn't define authorities twice. Define it **either** in `authorities` **or** in private claims.
If your application code just check authorities with standard SpEL (`hasAuthority`, `hasRole`, etc.), first option is clearly the easiest, less verbose and most readable way (and it already works).
The second option is only necessary if your application code explicitely accesses `KeycloakRessourceAccess`, which I personaly discourage as it makes it strongly adherent to Keycloak (migrating to another OIDC authorization server would be painful).

**Comment by ch4mpy** [comment]
There is a pitfall with htis feature: to my understanding, keycloak lib only adds to authorities the roles from a single resource access (the one configured with `` property. I don't have in mind a good way to retrieve such a config property during the tests right now and would rather map all roles from all resource-accesses.

But, again, this unit (not integration) testing and roles parsing doesn't involve application authorities mappers (which can do about anything like adding prefix, modifying case, append stuff, or even add or ignore roles) and configuring `authorities` with already parsed roles should be the prefered way.

Here is the modified test for the solution I propose:
``` java
	// @formatter:off
	@Test
	@WithMockKeycloakAuth(
			authorities = {"USER", "AUTHORIZED_PERSONNEL" },
			claims = @OpenIdClaims(
					sub = "42",
					jti = "123-456-789",
					nbf = "2020-11-18T20:38:00Z",
					sessionState = "987-654-321",
					email = "ch4mp@c4-soft.com",
					emailVerified = true,
					nickName = "Tonton-Pirate",
					preferredUsername = "ch4mpy",
					otherClaims = @Claims(jsonObjectClaims = @JsonObjectClaim(name = "foo", value = OTHER_CLAIMS))),
			accessToken = @KeycloakAccessToken(
					realmAccess = @KeycloakAccess(roles = { "TESTER" }),
					authorization = @KeycloakAuthorization(permissions = @KeycloakPermission(rsid = "toto", rsname = "truc", scopes = "abracadabra")),
					resourceAccess = {
							@KeycloakResourceAccess(resourceId = "resourceA", access = @KeycloakAccess(roles = {"A_TESTER"})),
							@KeycloakResourceAccess(resourceId = "resourceB", access = @KeycloakAccess(roles = {"B_TESTER"}))}))
	// @formatter:on
	public void whenAuthenticatedWithKeycloakAuthenticationTokenThenCanGreet() throws Exception {
		api
				.get("/greet")
				.andExpect(status().isOk())
				.andExpect(content().string(startsWith("Hello ch4mpy! You are granted with ")))
				.andExpect(content().string(containsString("AUTHORIZED_PERSONNEL")))
				.andExpect(content().string(containsString("USER")))
				.andExpect(content().string(containsString("TESTER")))
				.andExpect(content().string(containsString("A_TESTER")))
				.andExpect(content().string(containsString("B_TESTER")));
	}
```

**Comment by schmitzhermes** [comment]
It works just fine - thank you.
One remark: the `3.1.14-jdk1.8` does not seem to be on maven central yet. Is this just a timing thing or do u need to deploy that manuall?

**Comment by ch4mpy** [comment]
I can see it on https://repo1.maven.org/maven2/com/c4-soft/springaddons/spring-security-oauth2-addons/ 

I deploy to [sonatype](https://oss.sonatype.org/service/local/staging/deploy/maven2/) which handles deployment to repo1.maven.org (this rarely takes more than 2 hours)
