### ISSUE TITLE
Rename Keycloack to Keycloak

### ISSUE THREAD

**Issue by pvannierop** [ch4mpy/spring-addons#4]
Hello, I have started using your utils and I am very happy with it. Thank you for sharing your code.

At many places Keycloak is wrongly spelled as Keycloa**c**k. I do not know whether you are aware of this. You may keep this for sake of backwards compatibility, but I could not resist to point this out :) :)

**Comment by pvannierop** [comment]
> Hello, I have started using your utils and I am very happy with it. Thank you for sharing your code.
> 
> At many places Keycloak is wrongly spelled as Keycloa**c**k. I do not know whether you are aware of this. You may keep this for sake of backwards compatibility, but I could not resist to point this out :)

**Comment by ch4mpy** [comment]
Lets fix the typo (you are the only other user I know :)
