### ISSUE TITLE
Move Keycloak related stuff in dedicated jar

### ISSUE THREAD

**Issue by ch4mpy** [ch4mpy/spring-addons#41]
Currently, KeycloakAuthenticationToken related stuff (among which @WithMockKeycloakAuth annotation and MockMvc request post-processor) are standing with other Authentication implementations stuff. This makeseverything depend on Keycloak libs (even if it's marked as optional)

It would be better to isolate Keycloak stuf in dedicated jar and remove any reference to Keycloak from the rest.

**Comment by tacerus** [comment]
Hi, is this the reason I am unable to use the `@WithMockKeycloakAuth` with `<artifactId>spring-security-oauth2-test-addons</artifactId>`? Is there a new Keycloak related testing library available on Maven?

**Comment by ch4mpy** [comment]
Hi @tacerus 

Funny you read closed issues before the [README](https://github.com/ch4mpy/spring-addons). I suggest you start from there, you'll find the right dependency to pull.

**Comment by tacerus** [comment]
I can't help but agree that in this case I missed the obvious. Thank you very much!

**Comment by ch4mpy** [comment]
You're welcome. It might highlight that README is now to long :/

**Comment by tacerus** [comment]
:-) Ah well, that's mostly the change log. Maybe it could move to a separate `.md` or to GitHub's "releases" section some time, but I personally don't mind it!
