### ISSUE TITLE
Found WebSecurityConfigurerAdapter as well as SecurityFilterChain. Please select just one.

### ISSUE THREAD

**Issue by Mario-Eis** [ch4mpy/spring-addons#54]
Keycloak makes use of the WebSecurityConfigurerAdapter. Since the helper now provides a SecurityFilterChain, all my tests are failing with the message "Found WebSecurityConfigurerAdapter as well as SecurityFilterChain. Please select just one.". How can this library be used together with the Keycloak Webmvc Adapter after https://github.com/ch4mpy/spring-addons/issues/47?

Last working version was 4.1.10

**Comment by ch4mpy** [comment]
Hi @Mario-Eis 

Which sample did you follow to setup your test? Did you have a quick look at readme at all?

Would you share your unit-test code?

Maybe did you @AutoConfigureSecurityAddons (which sets-up spring-boot 2.7+ seb-security) when [the sample for KeycloakAuthenticationToken](https://github.com/ch4mpy/spring-addons/blob/master/samples/webmvc-keycloakauthenticationtoken) clearly [doesn't](https://github.com/ch4mpy/spring-addons/blob/a504c2992805b2c1586d6545802db79f5cd3724d/samples/webmvc-keycloakauthenticationtoken/src/test/java/com/c4_soft/springaddons/samples/webmvc_keycloakauthenticationtoken/GreetingControllerAnnotatedTest.java#L30).

If that's the case
- quick fix: remove @AutoConfigureSecurityAddons
- future-proof solution: do not use Keycloak libs at all in your resource server. Use either this lib auto-configuration (and OAuthentication<OpenidClaimSet>) or spring-security manual configuration (with JwtAuthenticationToken)

With second option, you'll be spring-boot 3 ready, can choose between webmvc or webflux app, and can switch your authorization-server from Keycloak to something else with minimum fuzz.

**Comment by Mario-Eis** [comment]
I used the configuration from the official Keycloak documentation in my web service: https://www.keycloak.org/docs/latest/securing_apps/#_spring_security_adapter
And behind the KeycloakWebSecurityConfigurerAdapter there is a WebSecurityConfigurerAdapter.

For my tests I use the spring-addons-keycloak to mock the authentication. So when I run the tests, spring-addons-keycloak are in the classpath. And it seems, as if they register a SecurityFilterChain.

**Comment by ch4mpy** [comment]
@Mario-Eis I know Keycloak spring adapter is still depending on WebSecurityConfigurerAdapter (reason for me writing you should use something else to be spring-boot 3 ready). This does not prevent `spring-addons-keycloak` from working. If you don't believe me, follow [first paragraph](https://github.com/ch4mpy/spring-addons#usage) of main readme: 
```bash
git clone https://github.com/ch4mpy/spring-addons.git
cd spring-addons
mvn test
```
You'll see a module named `webmvc-keycloakauthenticationtoken` with passing unit-test. If you open your IDE and browse to `spring-addons/samples/webmvc-keycloakauthenticationtoken`, you'll see that it's just an ordinary spring-boot app with Keycloak dependencies and properties (and various flavors of unit tests).

Also you answer to none of my questions. So unless you provide me with your pom (or gradle), web-security conf and unit-test, there is nothing I can do for you.

**Comment by ch4mpy** [comment]
> The security-oauth2-... are pulled automatically. Should they be ignored?

Good catch, this transient dependency on `spring-security-oauth2-webmvc-addons` is useless and should be removed. You can ignore it untill next release (but I don't believe it will solve your problem by itself).

**Comment by Mario-Eis** [comment]
Well, actually it (4.4.8) did solve my problem 😀

**Comment by ch4mpy** [comment]
> Well, actually it (4.4.8) did solve my problem

Good to read.

You should really consider dropping Keycloak libs. Give a try to [this instead](https://github.com/ch4mpy/spring-addons/tree/master/samples/tutorials/resource-server_with_oauthentication)

**Comment by Mario-Eis** [comment]
> You should really consider dropping Keycloak libs. Give a try to [this instead](https://github.com/ch4mpy/spring-addons/tree/master/samples/tutorials/resource-server_with_oauthentication)

I will consider it! Thanks!

**Comment by ch4mpy** [comment]
> I use spring boot, but with a part webmvc manual configuration (its complicated ;) )

Then, you might have JwtAuthenticationToken instances in runtime security-context. If so, `@WithMockJwtAuth` from `spring-security-oauth2-test-webmvc-addons` might be a better fit than `@WithMockKeycloakAuth`.

Plus, you can already bump to spring-boot 2.7 (need to give an eye to spring-boot doc to stop extending `WebSecurityConfigurerAdapter`)

In any case, you should really have a look at [that tutorial](https://github.com/ch4mpy/spring-addons/tree/master/samples/tutorials/resource-server_with_oauthentication), it should greatly simplify your conf.
