### ISSUE TITLE
resource-server_with_jwtauthenticationtoken doesn't work

### ISSUE THREAD

**Issue by zamek42** [ch4mpy/spring-addons#55]
**Describe the bug**
I tried to run your resource-server_with_jwtauthenticationtoken demo, with mvn spring-boot:run, but when I try to get /greet I've got an exception: 

[nio-8080-exec-9] o.s.security.web.FilterChainProxy        : Securing GET /greet
[nio-8080-exec-9] o.s.security.web.FilterChainProxy        : Invoking DisableEncodeUrlFilter (1/15)
[nio-8080-exec-9] o.s.security.web.FilterChainProxy        : Invoking ChannelProcessingFilter (2/15)
[nio-8080-exec-9] o.s.s.w.a.c.ChannelProcessingFilter      : Request: filter invocation [GET /greet]; ConfigAttributes: [REQUIRES_INSECURE_CHANNEL]
[nio-8080-exec-9] o.s.security.web.FilterChainProxy        : Invoking WebAsyncManagerIntegrationFilter (3/15)
[nio-8080-exec-9] o.s.security.web.FilterChainProxy        : Invoking SecurityContextPersistenceFilter (4/15)
[nio-8080-exec-9] s.s.w.c.SecurityContextPersistenceFilter : Set SecurityContextHolder to empty SecurityContext
[nio-8080-exec-9] o.s.security.web.FilterChainProxy        : Invoking HeaderWriterFilter (5/15)
[nio-8080-exec-9] o.s.security.web.FilterChainProxy        : Invoking CorsFilter (6/15)
[nio-8080-exec-9] o.s.security.web.FilterChainProxy        : Invoking CsrfFilter (7/15)
[nio-8080-exec-9] o.s.security.web.csrf.CsrfFilter         : Did not protect against CSRF since request did not match And [CsrfNotRequired [TRACE, HEAD, GET, OPTIONS], Not [Or [org.springframework.security.config.annotation.web.configurers.oauth2.server.resource.OAuth2ResourceServerConfigurer$BearerTokenRequestMatcher@5b9499fe]]]
[nio-8080-exec-9] o.s.security.web.FilterChainProxy        : Invoking LogoutFilter (8/15)
[nio-8080-exec-9] o.s.s.w.a.logout.LogoutFilter            : Did not match request to Ant [pattern='/logout', POST]
[nio-8080-exec-9] o.s.security.web.FilterChainProxy        : Invoking BearerTokenAuthenticationFilter (9/15)
[nio-8080-exec-9] .o.s.r.w.BearerTokenAuthenticationFilter : Did not process request since did not find bearer token
[nio-8080-exec-9] o.s.security.web.FilterChainProxy        : Invoking RequestCacheAwareFilter (10/15)
[nio-8080-exec-9] o.s.security.web.FilterChainProxy        : Invoking SecurityContextHolderAwareRequestFilter (11/15)
[nio-8080-exec-9] o.s.security.web.FilterChainProxy        : Invoking AnonymousAuthenticationFilter (12/15)
[nio-8080-exec-9] o.s.s.w.a.AnonymousAuthenticationFilter  : Set SecurityContextHolder to AnonymousAuthenticationToken [Principal=anonymousUser, Credentials=[PROTECTED], Authenticated=true, Details=WebAuthenticationDetails [RemoteIpAddress=0:0:0:0:0:0:0:1, SessionId=null], Granted Authorities=[ROLE_ANONYMOUS]]
[nio-8080-exec-9] o.s.security.web.FilterChainProxy        : Invoking SessionManagementFilter (13/15)
[nio-8080-exec-9] o.s.s.w.session.SessionManagementFilter  : Request requested invalid session id 5B6D1B1AEB30B6F27F9CB44FEAE5DFDB
[nio-8080-exec-9] o.s.security.web.FilterChainProxy        : Invoking ExceptionTranslationFilter (14/15)
[nio-8080-exec-9] o.s.security.web.FilterChainProxy        : Invoking FilterSecurityInterceptor (15/15)
[nio-8080-exec-9] edFilterInvocationSecurityMetadataSource : Did not match request to Ant [pattern='/actuator/health/readiness'] - [permitAll] (1/4)
[nio-8080-exec-9] edFilterInvocationSecurityMetadataSource : Did not match request to Ant [pattern='/actuator/health/liveness'] - [permitAll] (2/4)
[nio-8080-exec-9] edFilterInvocationSecurityMetadataSource : Did not match request to Ant [pattern='/v3/api-docs/**'] - [permitAll] (3/4)
[nio-8080-exec-9] o.s.s.w.a.i.FilterSecurityInterceptor    : Did not re-authenticate AnonymousAuthenticationToken [Principal=anonymousUser, Credentials=[PROTECTED], Authenticated=true, Details=WebAuthenticationDetails [RemoteIpAddress=0:0:0:0:0:0:0:1, SessionId=null], Granted Authorities=[ROLE_ANONYMOUS]] before authorizing
[nio-8080-exec-9] o.s.s.w.a.i.FilterSecurityInterceptor    : Authorizing filter invocation [GET /greet] with attributes [authenticated]
[nio-8080-exec-9] o.s.s.w.a.expression.WebExpressionVoter  : Voted to deny authorization
[nio-8080-exec-9] o.s.s.w.a.i.FilterSecurityInterceptor    : Failed to authorize filter invocation [GET /greet] with attributes [authenticated] using AffirmativeBased [DecisionVoters=[org.springframework.security.web.access.expression.WebExpressionVoter@1d4fb213], AllowIfAllAbstainDecisions=false]
[nio-8080-exec-9] o.s.s.w.a.ExceptionTranslationFilter     : Sending AnonymousAuthenticationToken [Principal=anonymousUser, Credentials=[PROTECTED], Authenticated=true, Details=WebAuthenticationDetails [RemoteIpAddress=0:0:0:0:0:0:0:1, SessionId=null], Granted Authorities=[ROLE_ANONYMOUS]] to authentication entry point since access is denied

org.springframework.security.access.AccessDeniedException: Access is denied

I've got a working keycloak server in http://localhost:38080 as I wrote it to my application.properties:
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:38080/realms/mikcube
I've a role named user, I've changed NICE-GUY to user in GreetingController. 

The web browser opens a simple login form instead of keycloak login form. 

test running succesfully I've changed my keycloak uri in its application.properties too. 
I've tried to debug it, and it reaches  filterChain(), authenticationConverter(), authoritiesConverter(), corsConfigurationSource() 
 methods. 

If I tried to get health info from actuator (localhost:8080/actuator/health/liveness, http localhost:8080/actuator/health/readiness it responds with 404.

)
**Expected behavior**
Authentication in my keycloak server

**Comment by ch4mpy** [comment]
Your web browser is not a REST client.  Use something like Postman to retrieve an access-token from Keycloak and build requests with Authorization header.

If you open your browser console, you should see that what you got is a 401 (Unauthorized which means that authorization is missing or invalid) and not a 302 (redirect to login). This is intended.

Building an auth2 `client` running in web browser is out of the scope of this tutorial which is focused on `resource-server` only. You can find a working sample of client with Angular [here](https://github.com/ch4mpy/user-proxies).

I'm surprised you get an exception: the browser you use probably chose to process that 401 error by displaying a login form and then retrying the request with Basic authentication header which should result in an other 401 (resource server expects a JWT issued by the configured authorization-server as `Bearer` Authorization, not a `basic` Authorization).

Would you share your complete modified project source on a drive or something (my email is ch4mp[at]c4-soft.com)?

**Comment by ch4mpy** [comment]
Thank you for sharing your project. I think it behaves as expected. Please see the [Prerequisites](https://github.com/ch4mpy/spring-addons/tree/master/samples/tutorials#prerequisites) section I just added to clarify what is required and how resource-servers behave.

You have a stack-trace because you set spring log-level to `TRACE`. The error you see is because `Authorization` header is missing, resulting in authentication failure.

I believe this error is further intercepted and a 401 is returned (you should be able to see return code value in your client console).

Regarding actuator, you need to enable it:
```properties
management.endpoint.health.probes.enabled=true
management.health.readinessstate.enabled=true
management.health.livenessstate.enabled=true
management.endpoints.web.exposure.include=*
```

I will add this to tutorial properties.
