### ISSUE TITLE
Can't compile the project

### ISSUE THREAD

**Issue by vksaamy** [ch4mpy/spring-addons#57]
The method toList() is undefined for the type Stream<SimpleGrantedAuthority> in return Stream.concat(realmRoles.stream(), Stream.concat(confidentialClientRoles.stream(), publicClientRoles.stream()))
					.map(SimpleGrantedAuthority::new).toList();

Using spring-boot 2.6.3 and spring spring resource server 5.6.1

**Comment by ch4mpy** [comment]
You should read the Readme and check your Java version.
