### ISSUE TITLE
Java 8 Compatibility

### ISSUE THREAD

**Issue by choweiyuan** [ch4mpy/spring-addons#6]
Hi I tried running with Java 8 and I get the following - 

```
import com.c4_soft.springaddons.security.oauth2.test.Defaults;
                                                    ^
  bad class file: C:\Users\****\.gradle\caches\modules-2\files-2.1\com.c4-soft.springaddons\spring-security-oauth2-test-addons\2.0.3\b489814912684ae9e3108e6f5759aeda854173aa\spring-security-oauth2-test-addons-2.0.3.jar(com/c4_soft/springaddons/security/oauth2/test/Defaults.class)
    class file has wrong version 55.0, should be 52.0
```

any chance of making your project Java 8 compatible? I checked the pom.xml and the java.version is 11

Thanks

**Comment by ch4mpy** [comment]
No, I wont support Java 8.

I code with recent (more functional) stream and collections APIs and don't want to drop six years (yeah, java 8 was release in 2014) of progress in the Java platform. sorry.
