### ISSUE TITLE
OIDC Identity Providers

### ISSUE THREAD

**Issue by navidmo** [ch4mpy/spring-addons#78]
Hi Jérôme @ch4mpy, thank you for your great work on customized resource servers and addon annotations. Do you have any pointers or starters for OIDC Identity Providers (I am following up on keycloak adapter depreciation)? I want to make custom authentication that utilizes some redis pub/sub messaging. Thank you for your help.

**Comment by ch4mpy** [comment]
This is a question about existing feature, not a request for a new one.

Replaced by https://github.com/ch4mpy/spring-addons/discussions/80
