### ISSUE TITLE
Java version error

### ISSUE THREAD

**Issue by SrMouraSilva** [ch4mpy/spring-addons#8]
When I try to use this library on Java 8, appears the following code:

```
com/c4_soft/springaddons/security/oauth2/test/annotations/keycloak/WithMockKeycloakAuth$Factory has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
java.lang.UnsupportedClassVersionError: com/c4_soft/springaddons/security/oauth2/test/annotations/keycloak/WithMockKeycloakAuth$Factory has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

I'm using `com.c4-soft.springaddons:spring-security-oauth2-test-webmvc-addons:2.1.0`

Please, release a Java 8 compatible ou informs in somewhere that it works only with Java 11.

**Comment by ch4mpy** [comment]
https://github.com/ch4mpy/spring-addons/issues/6.

Java 8 was released more than 6 years ago and I use collections API improvements.

I suggest you bump your Java version.

**Comment by SrMouraSilva** [comment]
So please put into Readme the minimum required version of java

**Comment by ch4mpy** [comment]
https://github.com/ch4mpy/spring-addons/blob/6040991746d9dfef6bb72d871fef86c9aff3d687/pom.xml#L46

**Comment by SrMouraSilva** [comment]
Ok, thanks!
