### ISSUE TITLE
Spring Data with webflux 

### ISSUE THREAD

**Issue by yacosta738** [ch4mpy/spring-addons#90]
Hello, great job with this library you have created. I wonder if it is possible for you to create an example where WebFlux and Spring Data are used to store authorities and some account data.

**Comment by ch4mpy** [comment]
For now this addons are focused on OAuth2 (tooling for tests and boot auto-configuration) and it would be a hell to maintain samples with all combinations of all spring projects. For instance here, do expect JDBC, JPA or R2DBC? If I start with spring-data, why not also include samples with integration and messaging? Etc.

However, if you intend to use R2DBC, you could start with [this archetype](https://github.com/ch4mpy/spring-addons/tree/master/archetypes/spring-addons-archetypes-webflux-singlemodule) and refer to samples to see how various types of `Authentication` can be configured in security context and how it can be injected as `@Controller` method parameter.

If you plan to use JPA, then start from one of the samples and then follow a spring-data tutorial to add persistence.
