### ISSUE TITLE
[NOT A BUG] about jwtAuthenticationConverter(authenticationConverter);

### ISSUE THREAD

**Issue by erdemcanturk** [ch4mpy/spring-addons#91]
Hi, 
Great repo. 
In this line `http.oauth2ResourceServer().jwt().jwtAuthenticationConverter(authenticationConverter);` I need a parameter jwt. How do you set it?

**Comment by ch4mpy** [comment]
Can you be more specific (provide the code you're working on)?

I don't see any `jwt` parameter in `http.oauth2ResourceServer().jwt().jwtAuthenticationConverter(authenticationConverter);`:
- `jwt()` is a method on `OAuth2ResourceServerConfigurer<HttpSecurity>` (from spring-security framework)
- `authenticationConverter` is a bean implementing `Converter<Jwt, ? extends AbstractAuthenticationToken>` (where the `Jwt` instance is provided by Spring at runtime when a JWT access-token is successfully decoded and validated

**Comment by erdemcanturk** [comment]
Sorry about that. I figured out I have to copy more for that configuration. That was my mistake at all and I figured it out.

Great repo by the way. Thank you for all
