### ISSUE TITLE
[Kotlin] Could not autowire. No beans of 'Converter<Map<String, Object>, Collection<GrantedAuthority>>' type found. 

### ISSUE THREAD

**Issue by JayAhn2** [ch4mpy/spring-addons#97]
**Describe the bug**
Hi. 

I've followed the sample code (samples/webmvc_oidcauthentication) in kotlin, but I've got syntax error in authenticationFactory bean registration as below.

```
Could not autowire. No beans of 'Converter<Map<String, Object>, Collection<GrantedAuthority>>' type found. 
```

Could you let me know what is missing here?
<img width="964" alt="image" src="https://user-images.githubusercontent.com/25868002/217432921-a4b42542-c186-4ffa-bf8c-6640ad0ab6a2.png">

**Code sample**
Ideally, provide me with :

```kt
@Configuration
@EnableMethodSecurity
class SecurityConfig {
  @Bean
  fun authenticationFactory(
    authoritiesConverter: Converter<Map<String, Any>, Collection<GrantedAuthority>>
  ): OAuth2AuthenticationFactory {
    return OAuth2AuthenticationFactory { bearerString, claims ->
      OAuthentication(
        OpenidClaimSet(claims),
        authoritiesConverter.convert(claims), bearerString
      )
    }
  }

  @Bean
  fun expressionInterceptUrlRegistryPostProcessor(): ExpressionInterceptUrlRegistryPostProcessor {
    // @formatter:off
    return ExpressionInterceptUrlRegistryPostProcessor { registry ->
      registry
        .requestMatchers("/secured-route").hasRole("AUTHORIZED_PERSONNEL")
        .anyRequest().authenticated()
    }
    // @formatter:on
  }
}
```
**Expected behavior**
No syntax error

**Additional context**

**Comment by ch4mpy** [comment]
I will not install IntelliJ to debug Kotlin code. Java with Lombok is good enough and works with all IDEs.

You might use `OAuth2AuthoritiesConverter` which is an alias for `Converter<Map<String, Object>, Collection<? extends GrantedAuthority>>`. Because of generics erasure, the context factory gets lost when there is more than one `Converter` bean and using such alias is viable workaround.

**Comment by JayAhn2** [comment]
@ch4mpy Yeah I just found that it works with `OAuth2AuthoritiesConverter`. Probably it would be clearer if you change the sample codes with `OAuth2AuthoritiesConverter` :)
