### ISSUE TITLE
Support Basic Authentication for specific url (eg. /swagger-ui/**)

### ISSUE THREAD

**Issue by JayAhn2** [ch4mpy/spring-addons#99]
**Is your feature request related to a problem? Please describe.**
I want to add basic authentication to specific urls like `/swagger-ui/index.html` or `/v3/api-docs/**`, but I'm not sure whether I can achieve it with this lib now or not. If possible, could you help me how to do it?

**Describe the solution you'd like**
Add basic auth server endpoints which cannot be secured by JWT.

**Comment by ch4mpy** [comment]
1. This is an issue tracker and neither a forum nor Stackoverflow
2. yes, Swagger can be can be secured with OAuth2:
    * the UI (`/swagger-ui/**`) either [natively](https://swagger.io/docs/open-source-tools/swagger-ui/usage/oauth2/) or with [an additional client security filter-chain](https://github.com/ch4mpy/spring-addons/tree/master/samples/tutorials/resource-server_with_ui)
    * the REST endpoints (`/v3/api-docs/**`) with the default security-filter chain from this repo starters
3. OAuth2 client-credentials flow allows to authenticate a programmatic client with an ID and a secret (just like you intend to do with basic auth
4. if you want to add basic auth to an endpoint (which makes little sense considering the points above), just create a separate security filterchain for it, just like it is done for the UI in the tutorial linked above

**Comment by JayAhn2** [comment]
Sorry! I will post this kind of questions in Stackoverflow. 

Thanks for your answer a lot!
